### ISSUE TITLE
webpack et al need to be in main dependencies

### ISSUE THREAD

**Issue by jedwards1211** [ramsaylanier/module-docs#6]
Because `html-webpack-plugin` and so forth are in this package's `devDependencies`, they're not installed when I add this package as a dep of my project.
```
$ yarn add --dev module-docs
andy@Andys-MBP-2:clarity (master) $ module-docs start
module.js:549
    throw err;
    ^

Error: Cannot find module 'html-webpack-plugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andy/clarity/node_modules/module-docs/lib/webpack.config.js:5:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by ramsaylanier** [comment]
@jedwards1211  thanks for bringing this to my attention - what an oversight!
